version: "3.9"

services:
  transit-db:
    image: postgis/postgis:16-3.4
    container_name: transit-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transit
    ports:
      - "5432:5432"
    volumes:
      - transit-db-data:/var/lib/postgresql/data
      - ./infrastructure/init:/docker-entrypoint-initdb.d

  api:
    build: ./apps/api
    container_name: commuter-api
    restart: always
    environment:
      PGHOST: transit-db        # <-- was db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: transit
      PGPORT: 5432
      PORT: 3000
    depends_on:
      - transit-db              # <-- was db
    ports:
      - "3000:3000"

  web:
    image: php:8.2-apache
    container_name: commuter-web
    restart: always
    volumes:
      - ./apps/web:/var/www/html
    depends_on:
      - api                     # this is correct; service name is "api"
    ports:
      - "8000:80"

volumes:
  transit-db-data:
